config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

 # get 'users/new'

  root 'static_page#home'

  get "help" => 'static_page#help'

  get "about"=>'static_page#about'

  get "signup" => "users#new"	
  
  get "login" =>"session#new"
  
  post "login" =>"session#create"
  
  delete "logout" =>"session#destroy"
	
	resources:users

  resources:blogs 

  resources:comments

  resources:likes

  resources:inventories
 
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user 
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :user_id, presence: true
  validates :title ,presence: true
  validates :content ,presence: true
  default_scope -> {order(created_at: :desc)}

  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@blog=current_user.blogs.build(blogs_params)
		if @blog.save
			flash[:success] = "Blog created!"
			redirect_to root_url
		else
			render 'static_page/home'
		end
	end


	def edit
		@blog=current_user.blogs.find_by(id:params[:id])
	end

	

	def destroy
		@blog.destroy
	flash[:success] = "Blog deleted"
redirect_to root_url
	end


def update
		@user=current_user
		@blog=@user.blogs.find_by(id:params[:id])
		if @blog.update_attributes(blogs_params)
			flash.now[:success] = "Blog updated"
redirect_to root_url

		else
			flash.now[:danger] = "Updating failed"
			redirect_to root_url
		end
	end



def correct_user
@blog = current_user.blogs.find_by(id: params[:id])
redirect_to root_url if @blog.nil?
end




	 

  private

  def blogs_params
  params.require(:blog).permit(:title,:content)
  end

  def logged_in_user
    if !logged_in?
      flash[:danger]="Please Log in"
      redirect_to root_url
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<li id="blog-<%= blog.id %>">

<%if blog.user.image %>
	<%= image_tag(blog.user.image.url,size: "40x40")%>
	<% end %>
<span class="user"><%= link_to blog.user.name, blog.user %></span>

<h2 class="content">Title:<%=blog.title%></h2>
<span class="content"><%= blog.content %></span>
<span class="timestamp">
Posted on <%=blog.created_at %> .
<% if current_user==blog.user %>
<%= link_to "delete", blog_path(blog), method: :delete,
data: { confirm: "You sure?" } %>
<%= link_to "edit", edit_blog_path(blog),method:"get",
data: { confirm: "You sure?" } %>
<% end %>
<% if logged_in? %>
<% if !already_liked?(current_user.id,blog.id)%>
<%=link_to "Like" ,likes_path(blog_id: blog.id,user_id: current_user.id),:method => :post,remote:true%>
<%else%>
<% @liker=blog.likes.find_by(user_id:current_user.id )%>
<%=link_to "Unlike" ,like_path(@liker.id),:method => :get,controller:"like",action:"show",remote:true %>
<%end%>
<%="#{like_no(blog.id)} likes"%>
<%=link_to "Add comment.." ,comment_path(blog.id)%>
<%end%>
<div id="comm">
	<%if blog.comments.any? %>
	<%@display_comments=blog.comments%>
	<%= render partial:'comments/comment' ,collection:@display_comments%>
	<%end%> 
</div>

</span>
</li>

app/views/blogs/edit.html.erb
<%= form_for(@blog) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%=f.label :title%>
<%=f.text_field :title %>
<%= f.text_area :content, placeholder: "Compose new blog..." ,class: 'form-control'%>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>