config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

 # get 'users/new'

  root 'static_page#home'

  get "help" => 'static_page#help'

  get "about"=>'static_page#about'

  get "signup" => "users#new"	
  
  get "login" =>"session#new"
  
  post "login" =>"session#create"
  
  delete "logout" =>"session#destroy"
	
	resources:users

  resources:blogs 

  resources:comments

  resources:likes

  resources:inventories
 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


before_action :logged_in_user 


	def show
		# render json: params and return
		@blog=Blog.find_by(id: params[:id])
		
		if @blog.nil?
			flash[:danger]="page 404"
			redirect_to root_url
		else
		@user=User.find_by(id: @blog.user_id)
		@comments=Comment.new
		@display_comments=@blog.comments
		respond_to do |format|
					format.html { }
					format.js   { }
					end
		end
	end

	def create 
		@blog=Blog.find_by(id: params[:id])
		#@user=User.find_by(id: @blog.user_id)
		@user=current_user
		@wy=@blog.comments.build(comment_params)
		@wy.user_id=@user.id
		if @wy.save
			flash.now[:success] = "Comment created!"
				 redirect_to request.referrer || root_url
				#render :show
			else
			render 'static_page/home'
		end
	end

	def edit
		@comments=Comment.find(params[:id])
		@blog=@comments.blog
		@user=@comments.user
		@display_comments=@blog.comments
		# render json:@display_comments and return
		@comm11=@display_comments
		respond_to do |format|
					format.html {  }
					format.js   { }
					end
	end

	def update
		
		@comm=Comment.find_by(id:params[:id])

		if @comm.update_attributes(comment_params)

			redirect_to request.referrer
			
			#redirect_to root_url	
		else
			flash[:danger]="edit comment failure"
			redirect_to root_url
		end

	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%=comment.id%>">

<%ret=find_user(comment.user_id)%>
<br>
<%if ret.image %>
	<%= image_tag(ret.image.url,size: "40x40")%>
	<% end %>
<span class="user"><%= link_to ret.name, ret %></span>
<h3><%=comment.body%></h3>

<%if current_user.id==comment.user_id%>
<%=link_to "edit comment...",edit_comment_path(comment), remote:true ,class:"editor", id:comment.id %>
<%end%>

</div>

app/views/comments/edit.html.erb
<% if @user.blogs.any? %>
	<h3>Blog</h3>
		<ol class="blogs">
		<%= render @blog %>
		</ol>
		<section class="blog_form">
			
			<%= render 'shared/comment_form' %>
		</section>
	
	<% end %>

app/views/comments/edit.js.erb
$("#comment-<%=@comments.id%>").html("<%= escape_javascript( render :partial => 'shared/comment_edit_form', object:@comments  )%>")

app/views/comments/show.html.erb
<% if @user.blogs.any? %>
	<h3>Blog</h3>
		<ol class="blogs">
		<%= render @blog %>
		</ol>
		<section class="blog_form">
			
			<%= render 'shared/comment_form' %>
		</section>
	
	<% end %>

app/views/comments/show.js.erb
$("#comm").html( "<%= escape_javascript(render partial:'comments/comment' ,collection:@display_comments) %>")