config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

 # get 'users/new'

  root 'static_page#home'

  get "help" => 'static_page#help'

  get "about"=>'static_page#about'

  get "signup" => "users#new"	
  
  get "login" =>"session#new"
  
  post "login" =>"session#create"
  
  delete "logout" =>"session#destroy"
	
	resources:users

  resources:blogs 

  resources:comments

  resources:likes

  resources:inventories
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "sample app", root_path, id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", root_path,onclick:"refre();" %></li>
<li><%= link_to "Help", new_inventory_path %></li>
<% if logged_in? %>
<li><%= link_to "Users", users_path, method:"get" %></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account <b class="caret"></b>
</a>
<ul class="dropdown-menu">
<li><%= link_to "Profile", current_user ,onclick:"refre();"%></li>
<li><%= link_to "Settings", edit_user_path(current_user), method: "get" %></li>
<li class="divider"></li>
<li>
<%= link_to "Log out", logout_path, method: "delete" %>
</li>
</ul>
</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>
</nav>
</div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= new_meth(yield(:title)) %></title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true ,'rails.validations'=> true%>
<%= csrf_meta_tags %>
<%= render('layouts/shim')%>
</head>
<body>
<%= render('layouts/header')%>
<div class="container">
<% flash.each do |message_type,message|%>
<div class="alert alert-<%=message_type%>"><%=message%>
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
</div>

<%end%>

<%= yield %>

<%= render('layouts/footer')%>
<%=debug(params) if Rails.env.development? %>
</div>
</body>
</html>